// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdijlW_2Oj0JcNCRsELaOCbmmVqlxRaVs',
    appId: '1:414801321795:web:f679deef28a5f73eaa99f6',
    messagingSenderId: '414801321795',
    projectId: 'heyconvo-f0f0c',
    authDomain: 'heyconvo-f0f0c.firebaseapp.com',
    storageBucket: 'heyconvo-f0f0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxA628-OhJAjsDlYC-2AjdsTOcCUCwY9k',
    appId: '1:414801321795:android:4d5f989a614dca05aa99f6',
    messagingSenderId: '414801321795',
    projectId: 'heyconvo-f0f0c',
    storageBucket: 'heyconvo-f0f0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDKs8Um4mp2gkCj-mmTZT_t6MwV1ar3Q',
    appId: '1:414801321795:ios:f19b938fd938fb76aa99f6',
    messagingSenderId: '414801321795',
    projectId: 'heyconvo-f0f0c',
    storageBucket: 'heyconvo-f0f0c.appspot.com',
    iosBundleId: 'com.example.heyconvo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDKs8Um4mp2gkCj-mmTZT_t6MwV1ar3Q',
    appId: '1:414801321795:ios:f19b938fd938fb76aa99f6',
    messagingSenderId: '414801321795',
    projectId: 'heyconvo-f0f0c',
    storageBucket: 'heyconvo-f0f0c.appspot.com',
    iosBundleId: 'com.example.heyconvo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdijlW_2Oj0JcNCRsELaOCbmmVqlxRaVs',
    appId: '1:414801321795:web:633c45fa566a3d54aa99f6',
    messagingSenderId: '414801321795',
    projectId: 'heyconvo-f0f0c',
    authDomain: 'heyconvo-f0f0c.firebaseapp.com',
    storageBucket: 'heyconvo-f0f0c.appspot.com',
  );
}
